version: '3'

services:
  users-api-josiney:
    build: .
    restart: always
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - payever

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - payever

  rabbitmq:
    image: rabbitmq:3.7-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBIT_USER}
      RABBITMQ_DEFAULT_USER: ${RABBIT_PASSWORD}
    volumes:
      - ./messaging/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
    networks:
      - payever

networks:
  payever:
    driver: bridge
